### ISSUE TITLE
an issue in bNTI.big.r 

### ISSUE THREAD

**Issue by ChiLiubio** [DaliangNing/iCAMP1#24]
Hi
Great package!
I found that there may be a unnecessary variable "c1" in  Line 95 lapply function in bNTI.big.r file. This may lead to an error when nworker=1.

Chi

**Comment by DaliangNing** [comment]
Very nice. I did not notice it since I never used nworker==1 before. In the newest version of iCAMP (version 1.5.8), I corrected similar careless mistakes in several functions, e.g. bNTI.big.r,  bNTI.big.cm.r,  dniche.r. Latest versions are available in [https://github.com/DaliangNing/iCAMP1/tree/master/RPackage/AllVersions](https://github.com/DaliangNing/iCAMP1/tree/master/RPackage/AllVersions)
