### ISSUE TITLE
Some confusions in using iCAMP

### ISSUE THREAD

**Issue by leozhangya** [DaliangNing/iCAMP1#36]
Hi Daliang,

I'm sorry to bother you, but I would like to ask you about two questions that have been troubling me for a long time

The first question is that can I perform separate iCAMP analysis for each group's data by setting the 'treat' parameter in 'iCAMP:bins' to NULL? Also, I want to ask if it's valid to describe the results as follows: for example, if I perform iCAMP analysis separately for Region A and Region B and find that diffusion limitation accounts for 60% in Region A and 50% in Region B, can I conclude that diffusion limitation plays a greater role in the construction of the community in Region A compared to Region B?

The reason I ask this question is because I currently have microbial data from multiple regions with control and experimental groups. I am considering directly performing iCAMP analysis on all the data, with the first column of the treatment file representing different regions and the second column representing different treatments. However, this calculation may not be appropriate. For example, when we divide the data by region, we cannot consider the impact of different treatments on microbial community construction. Similarly, dividing the data by treatment may overlook the influence of different regions. Of course, I believe I can solve this problem by pairwise comparison, but this may result in a cumbersome presentation of results. Therefore, it would be very convenient to perform iCAMP analysis separately for each group and then compare the results if feasible.

Maybe what I'm most concerned about is whether the results of iCAMP analysis on a microbiome will differ significantly depending on the presence or absence of a treatment file or different comparison objects (for example, comparing with sample A under condition A for the first time and with sample B under condition B for the second time). Because I think the assembly of microbiome in a certain group will not be changed by how they compare with other group. And do you have any better suggestions for this issue?

Another question I have is that after I conducted iCAMP analysis, my treatment file was divided into two groups: RS and RP. In the file named "ProcessImportance_EachGroup," besides the relative proportion of each ecological process for RS and RP, there is also a row named "RS_vs_RP." Could you please explain what this row represents?

And by the way could you give me some general rule for choosing the most appropriate bin.size.limit?

Best regards,

**Comment by DaliangNing** [comment]
(1) I generally recommend pooling all samples together to perform iCAMP. When samples are from different regional pools (i.e., under different metacommunities), you may use the function icamp.cm in iCAMP (version >=1.5.2) to specify the regional pool of each sample.  icamp.cm example is in step 9.3.2 of iCAMP example code: [https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r](https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r)

(2) To draw any conclusion of the comparison, you need to have the P value to prove the significance. See step 11 bootstrapping test (icamp.boot) in example R code ([https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r](https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r))

(3) if you have enough replicates in each treatment in each region, you may divide the samples with 'treatment x region'. for example, if you have two treatments in each of three regions, you may divide the samples into 6 groups. The bootstrapping test (icamp.boot, Step 11 of the example) can tell you significance of the pairwise comparison.

(4) The function icamp.big does not need to input treatment information. Its output is not affected by treatment information. The function icamp.cm allows you to specify different regional pools of different samples, which is more about locations rather than treatment.  Treatment information will surely affect the summary of each treatment when using icamp.bin, icamp.boot, etc.

(5) iCAMP is to evaluate the relation influence of each ecological process on beta diversity in the turnover between each two samples. If the two samples are within the same treatment, e.g., 'RS', the results are counted in the process importance in 'RS' group. If the two samples are from different treatments, e.g., one from 'RS', the other from 'RP', the results are counted in the process importance in 'RS-vs-RP'.

**Comment by leozhangya** [comment]
Thank you for your clear and detailed explanation！
