### ISSUE TITLE
How to evaluate the different results resulting from different methods

### ISSUE THREAD

**Issue by diego00012138** [DaliangNing/iCAMP1#40]
Dear Ning
    Because I am new to Null model , I tried every methods like tNST,pNST,iCAMP,qpen,etc. BUT I got completely different results.
    I feed the data of two groups named T and W. 
    From tNST,i got
![60a2e5a3b71a850fa3399a2210b695e](https://github.com/DaliangNing/iCAMP1/assets/101499808/e64f45a3-adca-46a0-9db0-827604e8f373)
    From pNST,i got
![02197c710fd7d57381191c2de9aa8e9](https://github.com/DaliangNing/iCAMP1/assets/101499808/a51f6333-09c8-4002-895e-88a0204c3f11)
    From iCAMP with the bmin as 72(determined by the maximum RAsig），i got
![f3562a111b2496394c687ebd24572ff](https://github.com/DaliangNing/iCAMP1/assets/101499808/4da24f01-4daa-48e8-baae-0cff022f0497)
![aa0226d5d3a8a172afacad8aeeb8ab9](https://github.com/DaliangNing/iCAMP1/assets/101499808/1189f64a-d647-474e-95d5-8b4bb61c2c50)
    From qpen (by the way ,i was confused by the function 'qpen.cm' with the para 'metagroup' which i gave the 'treat' like the 
    other processes, but the qpen.cm was interrupted with an error. AND the reason i use 'qpen.cm' was that I can't get individual 
    results for each group from 'qpen', which i think i get  from 'qpen.test' maybe ? Am i right?) , i got
![8bf0b0c870f0610b278c7a3991c1846](https://github.com/DaliangNing/iCAMP1/assets/101499808/1a3bbd3e-58ff-4480-8d02-ab4f10b3b110)
Sincerely

**Comment by DaliangNing** [comment]
The absolute value of 'relative importance of stochastic processes' can rarely be the same. When different methods showed the same relative trend, e.g., stochasticity increased or decreased, you may draw some reliable conclusion. Generally, pNST is better than tNST, since dispersal limitation or homogenizing dispersal, which are stochastic processes, may be counted as deterministic in tNST. If different phylogenetic groups are governed by totally different processes and their relative abundances are comparable, iCAMP is theoretically better than QPEN. However, each statistical method has its special assumptions which can be not valid in real cases with complex situations, thus we say it will be more reliable if multiple methods show the same relative change trend.

**Comment by DaliangNing** [comment]
About qpen function: yes, you can use qpen.test to get summary of each group.  the function qpen.cm means to assign different metacommunities for different samples.

**Comment by diego00012138** [comment]
Dear Ning
Thanks a lot ! AND  I was wondering if there was a way to get the bin tree conveniently from the results of iCAMP, can you give me a suggestion?
Sincerely

**Comment by DaliangNing** [comment]
You may use the most abundant taxon (top taxon) in each bin to represent the bin then extract the bin-top-taxa tree by function keep.tip in R package ape. Top taxon of each bin is available in the element Bin.TopClass of the output of function icamp.bins (see step 10 in example R code [https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r](https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r))
