### ISSUE TITLE
Question about results of QPEN

### ISSUE THREAD

**Issue by qingyu-wi** [DaliangNing/iCAMP1#43]
Hi,
i got some confusions about my results "ALL.QPEN.Bootstrapping.Summary.csv"
![image](https://github.com/DaliangNing/iCAMP1/assets/65074570/15ccfa1a-974a-4f0a-aa71-459eba1fab75)
in this figure, the management group "S", which relative importance of assembly process is zero except HoS, but it seems irrational?
if it is needed, i can upload extra materials for checking

Best regards,

**Comment by DaliangNing** [comment]
You can see the minimum betaNTI in the group "S" is still lower than -2, which means all pairwise phylogenetic beta diversity values (betaMNTD) were significantly lower than null expectation. 100% on one process is rare but can happen when using the method QPEN. Yes, it is not reasonable, which is why we further develop iCAMP. You may check whether there is any mistake (e.g., Tree). If no mistake, you may try iCAMP to assess the relative importance of each process.

**Comment by DaliangNing** [comment]
I hope your problem has been solved. If no more questions, I will close this issue soon.
