### ISSUE TITLE
Hi, Daliang

### ISSUE THREAD

**Issue by DUANZIHAOO** [DaliangNing/iCAMP1#44]
It seems like something wrong happened in ''icres=iCAMP::icamp.big''.

icres=iCAMP::icamp.big(comm=comm, pd.desc = pd.big$pd.file, pd.spname=pd.big$tip.label,
                       pd.wd = pd.big$pd.wd, rand = rand.time, tree=tree,
                       prefix = prefix, ds = 0.2, pd.cut = NA, sp.check = TRUE,
                       phylo.rand.scale = "within.bin", taxa.rand.scale = "across.all",
                       phylo.metric = "bMPD", sig.index=sig.index, bin.size.limit = bin.size.limit, 
                       nworker = nworker, rtree.save = FALSE, detail.save = TRUE, 
                       qp.save = FALSE, detail.null = FALSE, ignore.zero = TRUE, output.wd = save.wd, 
                       correct.special = TRUE, unit.sum = rowSums(comm), special.method = "depend",
                       ses.cut = 1.96, rc.cut = 0.95, conf.cut=0.975, omit.option = "no",meta.ab = NULL)

----bMPD bin i=27 in 67 ---- Wed Nov  1 18:25:33 2023
Now calculating observed betaMPD. Begin at Wed Nov  1 18:25:33 2023. Please wait...
Now randomizing by parallel computing. Begin at Wed Nov  1 18:25:35 2023. Please wait...
Now fixing special cases. Begin at Wed Nov  1 18:27:02 2023. Please wait...
All match very well.
Now calculating observed MPD. Begin at Wed Nov  1 18:27:02 2023. Please wait...
Now randomizing by parallel computing. Begin at Wed Nov  1 18:27:04 2023. Please wait...
Error in checkForRemoteErrors(val) : 
  4 nodes produced errors; first error: invalid 'size' argument

I have modified the format of ASV (absolute abundance, integers) table. However, the same error is still present.
I would greatly appreciate it if you could help me solve the error. Thanks for your time.

**Comment by DaliangNing** [comment]
You may send me (ningdaliang@ou.edu) the input files and your code via email to debug.

**Comment by DaliangNing** [comment]
The error was because the total abundance sum in each sample was too large (>10 ^ 12), which costs too much time for taxonomic null model algorithm.

Theoretically, it is more reasonable to use absolute abundance, although it is rarely used (because most studies cannot estimate absolute abundances). My suggestion: Once you get the raw ASV table (not rarefied to the same sequencing depth), calculate a certain resampling depth for each sample. This resampling depth should be proportional to the total copies per g (total abundance sum per gram sample) in this sample. Then, resample, e.g., use rrarefy in vegan package. So, after resampling, the ratio of abundance sums between two samples is equal to the ratio of the copies per g in the two samples. Then, we get an ASV table with only integers (suitable for null models), and the value of each ASV in each sample reflects the absolute abundance of the ASV.
