### ISSUE TITLE
erro Now summarizing method=CbMPDiCbraya i=1 j=1. Sat Mar  9 23:34:20 2024 Error in oldname[j, 1:2] : subscript out of bounds

### ISSUE THREAD

**Issue by Panda-smile** [DaliangNing/iCAMP1#53]
@DaliangNing  (use 9.1  step nalysis ) Hello professor, I have the following error when running the program. How should I solve it?
<img width="604" alt="image" src="https://github.com/DaliangNing/iCAMP1/assets/143200215/204909f2-0893-4b9b-8c9d-c8ee6e76aa2a">
Now summarizing method=CbMPDiCbraya i=1 j=1. Sat Mar  9 23:34:20 2024
Error in oldname[j, 1:2] : subscript out of bounds

**Comment by DaliangNing** [comment]
This error was usually because there was only one treatment, but 'between.group=TRUE'. Please check your 'treat' table; if there is only one group (treatment), please set between.group=FALSE; if there is multiple groups (treatments), please send me icres, treat, clas (save them as rda files) to debug.

**Comment by makerer5** [comment]
@DaliangNing  Hello professor,I had the same error and I saw the solution you gave was: set between.group=FALSE. I followed the tutorial on IEG3 and I don't know how to set "set between.group=FALSE".

**Comment by DaliangNing** [comment]
@makerer5  In the function 'iCAMP' on our web-based pipeline (http://ieg3.rccc.ou.edu:8080/), the option 'Summarize for between-group turnovers?' is about 'between.group', and the default setting is 'No' which means 'between.group=FALSE'. If you used default setting, your error is probably not due to 'between.group' setting. You may let me know your username on the pipeline to debug, or explore R package version.

**Comment by makerer5** [comment]
@DaliangNing Hello professor,My username in IEG3 is '' 1297622511yg@gmail.com'', and my working environment is ''fungi''. I am also trying to use R code to explore the results when treatment is a group

**Comment by DaliangNing** [comment]
@makerer5  the problem is solved. You may check the latest result files in your galaxy pipeline history 'fungi'.

**Comment by DaliangNing** [comment]
The error on Galaxy pipeline can happen when all samples are belong to the same group. I have revised the backend script to consider this kind of special cases. 

Similarly, when using the function icamp.boot in R package, if there is only one group, you need to set compare as FALSE; otherwise, the function will only return similar error.

**Comment by makerer5** [comment]
Dear Professor,

I sincerely thank you for your help and guidance in solving the difficulties in my scientific research. Also, you pointed out a possible problem when using the icamp.boot function in the R package, which is that the compare parameter needs to be set to FALSE when there is only one group. This tip was very helpful in my research and I am deeply grateful for your generosity in sharing your knowledge and experience.
Yang Guo



At 2024-04-19 07:20:40, "Daliang Ning" ***@***.***> wrote:

The error on Galaxy pipeline can happen when all samples are belong to the same group. I have revised the backend script to consider this kind of special cases.

Similarly, when using the function icamp.boot in R package, if there is only one group, you need to set compare as FALSE; otherwise, the function will only return similar error.

**Comment by DaliangNing** [comment]
@Panda-smile  sorry for my late response. Your error is caused by 'treat'.
iCAMP is based on beta diversity (pairwise dissimilarity between samples), thus each group must have at least 2 samples to provide between-sample beta diversity. Actually, a group had better include 6 or more samples to get relatively reliable null model estimations. But your 'treat' table (below) has multiple groups that only have a single sample.

    Management     Location
FQ1        FQ1           Qu
FQ2        FQ2           Qu
CP          CP           Qu
SC          SC           Qu
DJ          DJ Fermentation

**Comment by xuyangr** [comment]
dear professor, I am having problems running icamp because my version of icamp is too low, but input is a abundance file so it is less than 1. In the case of not updating the version, I would like to know whether it is possible to directly expand the abundance data by 100,000 times as the input file, so that the results of the calculation will be affected? Looking forward to your reply
.

**Comment by DaliangNing** [comment]
You can download the latest version of iCAMP from [https://github.com/DaliangNing/iCAMP1/tree/master/RPackage/AllVersions](https://github.com/DaliangNing/iCAMP1/tree/master/RPackage/AllVersions). 

Sorry, I do not fully understand your question. I guess you have 'relative abundance' data where the sum of each sample is 100%. If so, you may set dirichlet=TRUE in icamp.big, see step 9.5 in example R code [https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r](https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r).
If you mean you are not able to install iCAMP recent versions with the ability to handle relative abundance data, you can try to transform the community data to "count" data table, e.g., dividing the whole matrix by the minimum positive number in the matrix, then round to integers.

**Comment by kelly-xia** [comment]
Dear Professor:
I encountered the following issues when conducting diversity analysis of iCAMP on Galaxy. I am not sure where the problem lies. Could you show and help me  figure it out? My account is 31000655@scau.edu.cn. I am looking forward to your reply. Thank you so much.

Fatal error: Exit code 1 ()
Now computing path. begin at Sat May 11 22:04:08 2024. Please wait...
Error in checkForRemoteErrors(val) : 
  2 nodes produced errors; first error: subscript out of bounds
Calls: <Anonymous> ... clusterApply -> staticClusterAp


Your Sincerely 
Kerry

> @xuyangr You can download the latest version of iCAMP from https://github.com/DaliangNing/iCAMP1/tree/master/RPackage/AllVersions.
> 
> Sorry, I do not fully understand your question. I guess you have 'relative abundance' data where the sum of each sample is 100%. If so, you may set dirichlet=TRUE in icamp.big, see step 9.5 in example R code https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r. If you mean you are not able to install iCAMP recent versions with the ability to handle relative abundance data, you can try to transform the community data to "count" data table, e.g., dividing the whole matrix by the minimum positive number in the matrix, then round to integers.

**Comment by pbrinker** [comment]
Dear @DaliangNing,
I encountered the same error as Panda, i.e. 
> 'Now summarizing method=CbMPDiCbraya i=1 j=1.
>  Error in oldname[j, 1:2] : subscript out of bounds'

This error only occurs when running on a newer mac (Sonoma 14.5) with an M1 Pro chip. The command runs fine on an older mac (with an intel chip) using the same input files and script.

I think the problem is that on the new mac the function 'icamp.big' changes how 'CbMPDiCbraya' is writen, from 'xxx**b**raya' to 'xxx**B**raya'. Due to this icamp.bins can't find the values. 

I have no idea why it's doing this, and how to fix it. So it would be great if you could help me with this.

Yours sincerly and thanks a lot,
Pina

**Comment by DaliangNing** [comment]
@pbrinker  I can figure out a solution if you can send me the "...detail.rda" file generated by icamp.big function (which has the input of icamp.bins) and your treatment informaiton table (for the input 'treat' in icamp.bins).

**Comment by DaliangNing** [comment]
@kelly-xia  I belive your problem was caused by the IDs in Tree (Otuxxx) do not match IDs in ASV table and classification table (OTUxxx). The package and pipeline are case-sensitive.
[https://github.com/DaliangNing/iCAMP1/issues/58](https://github.com/DaliangNing/iCAMP1/issues/58)

> Dear Professor: I encountered the following issues when conducting diversity analysis of iCAMP on Galaxy. I am not sure where the problem lies. Could you show and help me figure it out? My account is [31000655@scau.edu.cn](mailto:31000655@scau.edu.cn). I am looking forward to your reply. Thank you so much.
> 
> Fatal error: Exit code 1 () Now computing path. begin at Sat May 11 22:04:08 2024. Please wait... Error in checkForRemoteErrors(val) : 2 nodes produced errors; first error: subscript out of bounds Calls: ... clusterApply -> staticClusterAp
> 
> Your Sincerely Kerry
> 
> > @xuyangr You can download the latest version of iCAMP from https://github.com/DaliangNing/iCAMP1/tree/master/RPackage/AllVersions.
> > Sorry, I do not fully understand your question. I guess you have 'relative abundance' data where the sum of each sample is 100%. If so, you may set dirichlet=TRUE in icamp.big, see step 9.5 in example R code https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r. If you mean you are not able to install iCAMP recent versions with the ability to handle relative abundance data, you can try to transform the community data to "count" data table, e.g., dividing the whole matrix by the minimum positive number in the matrix, then round to integers.

**Comment by pbrinker** [comment]
Dear Daliang Ning,
Thanks a lot for your help! I found a way to fix the problem. My metadata file caused the problem. It worked fine after minimising my treatment information to only letters.

thanks again; all the best 
Pina

**Comment by kelly-xia** [comment]
Dear Professor Ning：

I am extremely grateful for your assistance despite your busy schedule. The issue has been resolved; it was due to using an unrooted phylogenetic tree. Both Galaxy and R require rooted trees. Thank you so much for your help!




Sincerely Kerry










At 2024-10-07 03:52:52, "Daliang Ning" ***@***.***> wrote:

@kelly-xia I belive your problem was caused by the IDs in Tree (Otuxxx) do not match IDs in ASV table and classification table (OTUxxx). The package and pipeline are case-sensitive.
#58

Dear Professor: I encountered the following issues when conducting diversity analysis of iCAMP on Galaxy. I am not sure where the problem lies. Could you show and help me figure it out? My account is ***@***.*** I am looking forward to your reply. Thank you so much.

Fatal error: Exit code 1 () Now computing path. begin at Sat May 11 22:04:08 2024. Please wait... Error in checkForRemoteErrors(val) : 2 nodes produced errors; first error: subscript out of bounds Calls: ... clusterApply -> staticClusterAp

Your Sincerely Kerry

@xuyangr You can download the latest version of iCAMP from https://github.com/DaliangNing/iCAMP1/tree/master/RPackage/AllVersions.
Sorry, I do not fully understand your question. I guess you have 'relative abundance' data where the sum of each sample is 100%. If so, you may set dirichlet=TRUE in icamp.big, see step 9.5 in example R code https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r. If you mean you are not able to install iCAMP recent versions with the ability to handle relative abundance data, you can try to transform the community data to "count" data table, e.g., dividing the whole matrix by the minimum positive number in the matrix, then round to integers.
