### ISSUE TITLE
Interpretation questions

### ISSUE THREAD

**Issue by Hewang11111** [DaliangNing/iCAMP1#60]
Dear Daliang,

I am using the formula to get the contribution of ecological processes: 
icres=iCAMP::icamp.big(comm=comm, pd.desc = pd.big$pd.file, pd.spname=pd.big$tip.label,
                       pd.wd = pd.big$pd.wd, rand = rand.time, tree=tree,
                       prefix = "no_seepage60", ds = 0.2, pd.cut = NA, sp.check = TRUE,
                       phylo.rand.scale = "within.bin", taxa.rand.scale = "across.all",
                       phylo.metric = "bMPD", sig.index="Confidence", bin.size.limit = bin.size.limit, 
                       nworker = nworker, memory.G = 45, rtree.save = FALSE, detail.save = TRUE, 
                       qp.save = FALSE, detail.null = FALSE, ignore.zero = TRUE, output.wd = save.wd, 
                       correct.special = TRUE, unit.sum = rowSums(comm), special.method = "depend",
                       ses.cut = 1.96, rc.cut = 0.95, conf.cut=0.975, omit.option = "no",meta.ab = NULL, 
                       taxo.metric="bray", transform.method=NULL,logbase=2, dirichlet=TRUE)

It works well and I get a table mentioned that I used the method CbMPDiCbray. Does it mean that I divide my bins based on phylogenetic diversity using a confidence level based on betaMPD and taxonomic β-diversities using confidence level based on Bray-Curtis (BC)? If so, I wonder does the computer already calculated the confidence level based on betaMPD instead of βNRI? Do the calculation still compare βNRI of 1.96 and RC of 0.95? If not, what is the calculation behind the contribution of individual ecological processes? 

I have one extra questions, if I am allowed. I have 73737 ASVs for 815 samples. In this case, I extend the bin size to 120. I think the binsize is too large and I am going to reduce it. What is your suggestions, do you think bin size of 48 is already enough for running, or I could try with 80 or larger?

Looking forward to your reply and I really need your help. Thank you very much for your time and patience.

Best regards,
He Wang

**Comment by DaliangNing** [comment]
(1) When you selected sig.index="Confidence" for icamp.big, betaNRI and RC will not be calculated. You can set sig.index="SES.RC” to get betaNRI and RC.
CbMPDiCbraya means use ‘confidence level’ rather than ‘standardized effect size’ (betaNRI) or ‘modified Raup-Crick metric’ (RC), which was strongly suggested by a reviewer of our iCAMP paper. Since the resutls did not change obviously by 'sig.index' setting, we still used betaNRI and RC in our iCAMP paer and explained in the supplementary information. ‘standardized effect size’ (betaNRI) assumes null model values follow normal distribution, thus confidence level could be better if it is actually not normal distribution. ‘RC’ is transformed confidence level. 

(2) Below is the code in RC.pc. If RC.pc is applied to a subcommunity or a bin or the null model algorithm changes the sum of a sample, defining unit.sum as rowSums(comm) can maintain the Bray-Cuitis values are based on the relative abundances in the entire community.

if (is.null(unit.sum)) {
                comit = comi/rowSums(comi)
                comit[which(rowSums(comi) == 0), ] = 0
                BC = vegan::vegdist(comit, method = "bray")
            }else {
                comit = comi/unit.sum
                comit[which(unit.sum == 0), ] = 0
                BC = vegan::vegdist(comit, method = "manhattan")/2
            }

(3) bin.size.limit had better be determined by phylogenetic signal test as showed in step 7 to 8 in the example R code:
[https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r](https://github.com/DaliangNing/iCAMP1/blob/master/Examples/SimpleOTU/icamp.test.r)

BTW, your ASV number is relatively large. If iCAMP calculation is very time consuming, please check page 4 ‘Reducing the taxa number’ in the supplementary information of the icamp paper [https://www.nature.com/articles/s41467-020-18560-z#Sec17](https://www.nature.com/articles/s41467-020-18560-z#Sec17)
