### ISSUE TITLE
choice of phylogenetic metric

### ISSUE THREAD

**Issue by adityabandla** [DaliangNing/iCAMP1#8]
Dear Ning,

I tried reproducing results from your Nat. Comm. paper. I get 658 bins (ds = 0.2, bin.size.limit = 12) as you report in the paper. However, when I had a look at the maximum and mean phylogenetic distances, it looks like a good number of bins have a fair number of OTUs which lie outside the signal threshold as a result of merging bins. In this case, will bNRI still provide reliable results? 

Regards, Adi

**Comment by DaliangNing** [comment]
bNRI is still fine, since the within-bin phylogenetic signal test is still significant. I tested many simulated datasets, where the final within-bin phylogenetic distances are mostly out of the threshold, but the quantitative performance (accuracy, precision, sensitivity, and specificity) is still good (as reported). Thus, the threshold from Mantel correlogram appears like a start point but not a sensitive parameter for the quantification.

However, as I pointed out in our communication, within-bin betaNTI can be good or even better than within-bin betaNRI if the phylogenetic signal within each bin is not strong enough. But in some cases, it is hard to tell whether it is 'enough' or not. It is always a good practice to estimate the relative importance of stochastic (neutral) processes with other methods (e.g. [NST](https://github.com/DaliangNing/NST)), then the metric leading to more consistent conclusion with other methods could be a better choice.
